name: shared_preferences
description: The key-value preference library for MPFlutter
publish_to: 'none'
homepage: https://github.com/mpflutter-plugins/shared_preferences
version: 1.0.0

dependencies:
  meta: ^1.3.0
  flutter:
    git:
      url: https://github.com/mpflutter/mpflutter
      path: packages/flutter
      ref: master
  mpcore:
    git:
      url: https://github.com/mpflutter/mpflutter
      path: packages/mpcore
      ref: master

dev_dependencies:
  pedantic: ^1.10.0

dependency_overrides:
  flutter:
    git:
      url: https://github.com/mpflutter/mpflutter
      path: packages/flutter
      ref: master
  mpcore:
    git:
      url: https://github.com/mpflutter/mpflutter
      path: packages/mpcore
      ref: master
  flutter_web_plugins:
    git:
      url: https://github.com/mpflutter/mpflutter
      path: packages/flutter_web_plugins
      ref: master

environment:
  sdk: ">=2.12.0 <3.0.0"
